// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: moretypes/v1/decimal.proto

package moretypes

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	String_ string `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moretypes_v1_decimal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_moretypes_v1_decimal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_moretypes_v1_decimal_proto_rawDescGZIP(), []int{0}
}

func (x *Decimal) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

var File_moretypes_v1_decimal_proto protoreflect.FileDescriptor

var file_moretypes_v1_decimal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x6f, 0x72, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x6f,
	0x72, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x18, 0xba, 0x48, 0x15, 0x72, 0x13, 0x32, 0x11, 0x5e, 0x28, 0x5c, 0x64, 0x2a,
	0x5c, 0x2e, 0x5c, 0x64, 0x2b, 0x24, 0x7c, 0x5c, 0x64, 0x2b, 0x29, 0x24, 0x52, 0x06, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x6e, 0x74, 0x6f, 0x70, 0x73, 0x2f, 0x6d, 0x6f, 0x72, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x72, 0x65, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_moretypes_v1_decimal_proto_rawDescOnce sync.Once
	file_moretypes_v1_decimal_proto_rawDescData = file_moretypes_v1_decimal_proto_rawDesc
)

func file_moretypes_v1_decimal_proto_rawDescGZIP() []byte {
	file_moretypes_v1_decimal_proto_rawDescOnce.Do(func() {
		file_moretypes_v1_decimal_proto_rawDescData = protoimpl.X.CompressGZIP(file_moretypes_v1_decimal_proto_rawDescData)
	})
	return file_moretypes_v1_decimal_proto_rawDescData
}

var file_moretypes_v1_decimal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_moretypes_v1_decimal_proto_goTypes = []interface{}{
	(*Decimal)(nil), // 0: moretypes.v1.Decimal
}
var file_moretypes_v1_decimal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moretypes_v1_decimal_proto_init() }
func file_moretypes_v1_decimal_proto_init() {
	if File_moretypes_v1_decimal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moretypes_v1_decimal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moretypes_v1_decimal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moretypes_v1_decimal_proto_goTypes,
		DependencyIndexes: file_moretypes_v1_decimal_proto_depIdxs,
		MessageInfos:      file_moretypes_v1_decimal_proto_msgTypes,
	}.Build()
	File_moretypes_v1_decimal_proto = out.File
	file_moretypes_v1_decimal_proto_rawDesc = nil
	file_moretypes_v1_decimal_proto_goTypes = nil
	file_moretypes_v1_decimal_proto_depIdxs = nil
}
